Datalogger: projects/Datalogger/inc/Datalogger.h File Reference
Datalogger.h File Reference
Functions
void disk_timerproc (void)
int main (void)
Function Documentation
disk_timerproc()
void disk_timerproc (void)
Referenced by diskTickHook().
main()
int main (void)
< Inicializar y configurar la plataforma.
Se hace un bypass del MPI6050, Acelerometro y Giroscopio acelerometro digital de 3 ejes, medicion hasta ±16g; y giroscopio digital de 3 ejes, medicion hasta ±2000 º/s.
< Inicializar HMC5883L.
< Inicializar UART_USB a 115200 baudios.
< Estructura RTC-
< Inicializar RTC.
< SPI configuration.
Inicializar el conteo de Ticks con resolucion de 10ms, con tickHook diskTickHook.
< Configura el delay no bloqueante, el cual se usa para determinar el tiempo de muestreo.
< Give a work area to the default drive.
Definition at line 147 of file Datalogger.c.
References angle, ArmaDateAndTime(), bw, CargaBrujuBuffDisco(), CargaDatosBuffDisco(), datosBuffer, delay1s, diskTickHook(), FILENAME, fp, fs, hmc5883l_x_raw, hmc5883l_y_raw, hmc5883l_z_raw, Mpu6050Bypass(), POSICION_ANGULO, POSICION_X, POSICION_Y, POSICION_Z, SendArchivoToUart(), TMUESTREO, and vectorR2ToAngle().