Datalogger: projects/Datalogger/src/Datalogger.c File Reference
Datalogger.c File Reference
#include "Datalogger.h"
#include "sapi.h"
#include <math.h>
#include "sapi_i2c.h"
#include "ff.h"
Macros
#define FILENAME "Datos.txt"
< Biblioteca FAT FS.
#define POSICION_DAY 0
Posicion del dato dia dentro de "datosBuffer".
#define POSICION_MONTH 3
Posicion del dato mes dentro de "datosBuffer".
#define POSICION_YEAR 6
Posiciona del dato año dentro de "datosBuffer".
#define POSICION_HOUR 12
Posicion del dato hora dentro de "datosBuffer".
#define POSICION_MIN 15
Posicion del dato minutos dentro de "datosBuffer".
#define POSICION_SEC 18
Posicion del dato segundos dentro de "datosBuffer".
#define POSICION_X 26
Posicion del dato coordenada X dentro de "datosBuffer".
#define POSICION_Y 35
Posicion del dato coordenada Y dentro de "datosBuffer".
#define POSICION_Z 44
Posicion del dato coordenada Z dentro de "datosBuffer".
#define POSICION_ANGULO 58
Posicion del dato angulo dentro de "datosBuffer".
#define POSICION_APUNTA 71
Posicion del dato dentro de "datosBuffer" de hacia donde apunta el modulo.
#define TMUESTREO 2000
Definicion del tiempo de muestreo.
Functions
char * itoa (int value, char *result, int base)
Funcion que se usa para convertir un entero a un ASCII.
void SendArchivoToUart (void)
Envia el archivo con los datos por la UART_USB.
void ArmaDateAndTime (rtc_t *rtc)
Almacena datos de la fecha y hora en el buffer.
void Mpu6050Bypass (void)
Habilita el Bypass del MPU6050.
void AlmacenaDatoRango (uint8_t dato, uint8_t posicion)
Almacena un dato en una posicion determinada del buffer.
void CargaDatosBuffDisco (int16_t dato, uint8_t posicion)
Carga X, Y, Z y Angulo en el buffer.
void CargaBrujuBuffDisco (int16_t angle)
Carga la direccion hacia donde apunta el modulo en el buffer.
int16_t vectorR2ToAngle (int16_t axis1, int16_t axis2)
Calculo del angulo.
bool_t diskTickHook (void *ptr)
Funcion que se ejecuta cada vez que ocurre un Tick.
int main (void)
Variables
static FATFS fs
FatFs work area needed for each volume.
static FIL fp
File object needed for each open file.
static UINT bw
Pointer to the variable to return number of bytes written.
static uint8_t dataBuff [10]
static uint8_t datosBuffer [] = " / / : : - x= y= z= Angulo= Apunta= \r\n"
static uint8_t strNorte [] = "Norte "
String "Norte".
static uint8_t strNoreste [] = "Noreste "
String "Noreste".
static uint8_t strEste [] = "Este "
String "Este".
static uint8_t strSudeste [] = "Sudeste "
String "Sudeste".
static uint8_t strSur [] = "Sur "
String "Sur".
static uint8_t strSuroeste [] = "Suroeste"
String "Suroeste".
static uint8_t strOeste [] = "Oeste "
String "Oeste".
static uint8_t strNoroeste [] = "Noroeste"
String "Noroeste".
static int16_t hmc5883l_x_raw
Variable que contiene el valor obtenido del eje X del HMC5883L.
static int16_t hmc5883l_y_raw
Variable que contiene el valor obtenido del eje Y del HMC5883L.
static int16_t hmc5883l_z_raw
Variable que contiene el valor obtenido del eje Z del HMC5883L.
static int16_t angle = 0
Variable que contiene el valor del angulo obtenido del calculo del X y Y.
delay_t delay1s
Estructura usada para el control del tiempo de muestreo.
Macro Definition Documentation
FILENAME
#define FILENAME "Datos.txt"
< Biblioteca FAT FS.
< Su propio archivo de cabecera. < Biblioteca sAPI. Funciones matematicas. < sAPI I2C header.Nombre del archivo en donde se guardaran los datos.
Definition at line 69 of file Datalogger.c.
Referenced by main(), and SendArchivoToUart().
POSICION_ANGULO
#define POSICION_ANGULO 58
Posicion del dato angulo dentro de "datosBuffer".
Definition at line 79 of file Datalogger.c.
Referenced by main().
POSICION_APUNTA
#define POSICION_APUNTA 71
Posicion del dato dentro de "datosBuffer" de hacia donde apunta el modulo.
Definition at line 80 of file Datalogger.c.
Referenced by CargaBrujuBuffDisco().
POSICION_DAY
#define POSICION_DAY 0
Posicion del dato dia dentro de "datosBuffer".
Definition at line 70 of file Datalogger.c.
Referenced by ArmaDateAndTime().
POSICION_HOUR
#define POSICION_HOUR 12
Posicion del dato hora dentro de "datosBuffer".
Definition at line 73 of file Datalogger.c.
Referenced by ArmaDateAndTime().
POSICION_MIN
#define POSICION_MIN 15
Posicion del dato minutos dentro de "datosBuffer".
Definition at line 74 of file Datalogger.c.
Referenced by ArmaDateAndTime().
POSICION_MONTH
#define POSICION_MONTH 3
Posicion del dato mes dentro de "datosBuffer".
Definition at line 71 of file Datalogger.c.
Referenced by ArmaDateAndTime().
POSICION_SEC
#define POSICION_SEC 18
Posicion del dato segundos dentro de "datosBuffer".
Definition at line 75 of file Datalogger.c.
Referenced by ArmaDateAndTime().
POSICION_X
#define POSICION_X 26
Posicion del dato coordenada X dentro de "datosBuffer".
Definition at line 76 of file Datalogger.c.
Referenced by main().
POSICION_Y
#define POSICION_Y 35
Posicion del dato coordenada Y dentro de "datosBuffer".
Definition at line 77 of file Datalogger.c.
Referenced by main().
POSICION_YEAR
#define POSICION_YEAR 6
Posiciona del dato año dentro de "datosBuffer".
Definition at line 72 of file Datalogger.c.
Referenced by ArmaDateAndTime().
POSICION_Z
#define POSICION_Z 44
Posicion del dato coordenada Z dentro de "datosBuffer".
Definition at line 78 of file Datalogger.c.
Referenced by main().
TMUESTREO
#define TMUESTREO 2000
Definicion del tiempo de muestreo.
Definition at line 81 of file Datalogger.c.
Referenced by main().
Function Documentation
AlmacenaDatoRango()
void AlmacenaDatoRango (uint8_t dato, uint8_t posicion)
Almacena un dato en una posicion determinada del buffer.
Parameters
[in] dato Dato a ser almacenado.
[in] posicion La posicion donde sera almacenado el "dato".
Returns
Nada...
La funcion es usada por "ArmaDateAndTime()", recibe un dato y una posicion, con estos datos almacena los datos de la hora y fecha dentro de "datosBuffer[]".
Definition at line 462 of file Datalogger.c.
References dataBuff, and datosBuffer.
Referenced by ArmaDateAndTime().
ArmaDateAndTime()
void ArmaDateAndTime (rtc_t * rtc)
Almacena datos de la fecha y hora en el buffer.
Parameters
[in] rtc Estructura tipo "rtc_t".
Returns
Nada...
La funcion es la encargada de almacenar en el buffer "datosBuffer[]" los datos de la fecha y hora, cada valor es almacenado en una posicion determinada dentro del buffer, estas posiciones estan en los define "POSICION_xxx".
Definition at line 413 of file Datalogger.c.
References AlmacenaDatoRango(), dataBuff, datosBuffer, itoa(), POSICION_DAY, POSICION_HOUR, POSICION_MIN, POSICION_MONTH, POSICION_SEC, and POSICION_YEAR.
Referenced by main().
CargaBrujuBuffDisco()
void CargaBrujuBuffDisco (int16_t angle)
Carga la direccion hacia donde apunta el modulo en el buffer.
Parameters
[in] angle Recibe el el angulo calculado por "vectorR2ToAngle()".
Returns
Nada...
La funcion recibira el angulo, y con el se procede a determinar la direccion (Norte, Este, etc), la direccion es almacenada en el buffer "datosBuffer[]", el cual es el que se grabara en la memoria SD/uSD.
Definition at line 569 of file Datalogger.c.
References datosBuffer, POSICION_APUNTA, strEste, strNoreste, strNoroeste, strNorte, strOeste, strSudeste, strSur, and strSuroeste.
Referenced by main().
CargaDatosBuffDisco()
void CargaDatosBuffDisco (int16_t dato, uint8_t posicion)
Carga X, Y, Z y Angulo en el buffer.
Parameters
[in] dato Datos obtenidos del HMC5883L X, Y, Z o Angulo calculado.
[in] posicion Es la posicion que ocupara "dato" en el buffer.
Returns
Nada...
La funcion recibira X, Y, Z o Angulo, junto con un dato de la posicion que el dato recibido ocupara en el buffer, este buffer sera el que se grabe en el archivo.
Definition at line 535 of file Datalogger.c.
References datosBuffer, and itoa().
Referenced by main().
diskTickHook()
bool_t diskTickHook (void * ptr)
Funcion que se ejecuta cada vez que ocurre un Tick.
Parameters
[in] ptr
Returns
1
Definition at line 296 of file Datalogger.c.
References disk_timerproc().
Referenced by main().
itoa()
char * itoa (int value, char * result, int base)
Funcion que se usa para convertir un entero a un ASCII.
Parameters
[in] value Valor a convertir.
[in] result Puntero donde se encuentra el resultado ASCII.
[in] base La base de la conversion ej.10 es decimal.
Returns
Un puntero, el cual apunta a los ASCII obtenidos.
Definition at line 321 of file Datalogger.c.
Referenced by ArmaDateAndTime(), and CargaDatosBuffDisco().
main()
int main (void)
< Inicializar y configurar la plataforma.
Se hace un bypass del MPI6050, Acelerometro y Giroscopio acelerometro digital de 3 ejes, medicion hasta ±16g; y giroscopio digital de 3 ejes, medicion hasta ±2000 º/s.
< Inicializar HMC5883L.
< Inicializar UART_USB a 115200 baudios.
< Estructura RTC-
< Inicializar RTC.
< SPI configuration.
Inicializar el conteo de Ticks con resolucion de 10ms, con tickHook diskTickHook.
< Configura el delay no bloqueante, el cual se usa para determinar el tiempo de muestreo.
< Give a work area to the default drive.
Definition at line 147 of file Datalogger.c.
References angle, ArmaDateAndTime(), bw, CargaBrujuBuffDisco(), CargaDatosBuffDisco(), datosBuffer, delay1s, diskTickHook(), FILENAME, fp, fs, hmc5883l_x_raw, hmc5883l_y_raw, hmc5883l_z_raw, Mpu6050Bypass(), POSICION_ANGULO, POSICION_X, POSICION_Y, POSICION_Z, SendArchivoToUart(), TMUESTREO, and vectorR2ToAngle().
Mpu6050Bypass()
void Mpu6050Bypass (void)
Habilita el Bypass del MPU6050.
Returns
Nada...
Debido a que el modulo utilizado para adquirir los datos es el GY-87 en el cual para acceder al HMC5883L hay que pasar por el MPU6050, esto se logra mediante la habilitacion del Serial Interface Bypass Mux.
Definition at line 491 of file Datalogger.c.
Referenced by main().
SendArchivoToUart()
void SendArchivoToUart (void)
Envia el archivo con los datos por la UART_USB.
Returns
Nada...
La funcion es la encargada de enviar el archivo que contiene los datos obtenidos del HMC5883L y los procesados, el envio se realiza por la UART_USB, se envian paquetes de 100 bytes consecutivos hasta completar la totalidad de datos almacenados.
Note
Faltaria completar la salida/procesamiento de los errores de archivo.
Definition at line 364 of file Datalogger.c.
References FILENAME, and fp.
Referenced by main().
vectorR2ToAngle()
int16_t vectorR2ToAngle (int16_t axis1, int16_t axis2)
Calculo del angulo.
Parameters
[in] axis1 Este dato es el que corresponde a la coordenada X.
[in] axis2 Este dato es el que corresponde a la coordenada Y.
Returns
Retorna el angulo (int16_t).
La funcion es la encargada de calcular el angulo en base a los datos del HMC5883L, ejes X e Y.
Definition at line 643 of file Datalogger.c.
References angle.
Referenced by main().
Variable Documentation
angle
int16_t angle = 0 static
Variable que contiene el valor del angulo obtenido del calculo del X y Y.
Definition at line 112 of file Datalogger.c.
Referenced by main(), and vectorR2ToAngle().
bw
UINT bw static
Pointer to the variable to return number of bytes written.
Definition at line 88 of file Datalogger.c.
Referenced by main().
dataBuff
uint8_t dataBuff[10] static
Buffer utilizado en la conversion de int a ascii y en la funcion que almacena los datos dentro de "datosBuffer".
Definition at line 91 of file Datalogger.c.
Referenced by AlmacenaDatoRango(), and ArmaDateAndTime().
datosBuffer
uint8_t datosBuffer[] = " / / : : - x= y= z= Angulo= Apunta= \r\n" static
Buffer donde se cargan los datos obtenidos y calculados para luego este ser almacenado en la tarjeta SD/uSD.
Definition at line 97 of file Datalogger.c.
Referenced by AlmacenaDatoRango(), ArmaDateAndTime(), CargaBrujuBuffDisco(), CargaDatosBuffDisco(), and main().
delay1s
delay_t delay1s
Estructura usada para el control del tiempo de muestreo.
Definition at line 115 of file Datalogger.c.
Referenced by main().
fp
FIL fp static
File object needed for each open file.
Definition at line 87 of file Datalogger.c.
Referenced by main(), and SendArchivoToUart().
fs
FATFS fs static
FatFs work area needed for each volume.
Definition at line 86 of file Datalogger.c.
Referenced by main().
hmc5883l_x_raw
int16_t hmc5883l_x_raw static
Variable que contiene el valor obtenido del eje X del HMC5883L.
Definition at line 109 of file Datalogger.c.
Referenced by main().
hmc5883l_y_raw
int16_t hmc5883l_y_raw static
Variable que contiene el valor obtenido del eje Y del HMC5883L.
Definition at line 110 of file Datalogger.c.
Referenced by main().
hmc5883l_z_raw
int16_t hmc5883l_z_raw static
Variable que contiene el valor obtenido del eje Z del HMC5883L.
Definition at line 111 of file Datalogger.c.
Referenced by main().
strEste
uint8_t strEste[] = "Este " static
String "Este".
Definition at line 101 of file Datalogger.c.
Referenced by CargaBrujuBuffDisco().
strNoreste
uint8_t strNoreste[] = "Noreste " static
String "Noreste".
Definition at line 100 of file Datalogger.c.
Referenced by CargaBrujuBuffDisco().
strNoroeste
uint8_t strNoroeste[] = "Noroeste" static
String "Noroeste".
Definition at line 106 of file Datalogger.c.
Referenced by CargaBrujuBuffDisco().
strNorte
uint8_t strNorte[] = "Norte " static
String "Norte".
Definition at line 99 of file Datalogger.c.
Referenced by CargaBrujuBuffDisco().
strOeste
uint8_t strOeste[] = "Oeste " static
String "Oeste".
Definition at line 105 of file Datalogger.c.
Referenced by CargaBrujuBuffDisco().
strSudeste
uint8_t strSudeste[] = "Sudeste " static
String "Sudeste".
Definition at line 102 of file Datalogger.c.
Referenced by CargaBrujuBuffDisco().
strSur
uint8_t strSur[] = "Sur " static
String "Sur".
Definition at line 103 of file Datalogger.c.
Referenced by CargaBrujuBuffDisco().
strSuroeste
uint8_t strSuroeste[] = "Suroeste" static
String "Suroeste".
Definition at line 104 of file Datalogger.c.
Referenced by CargaBrujuBuffDisco().