HMC+RTC=>SD: sapi_examples_AmA/edu-ciaa-nxp/ej22_SD_BrujulaIIC_RTC_Doc/src/mmc.c File Reference
mmc.c File Reference
#include "board.h"
#include "diskio.h"
Macros
#define CMD0 (0x40+0) /* GO_IDLE_STATE */
#define CMD1 (0x40+1) /* SEND_OP_COND (MMC) */
#define ACMD41 (0xC0+41) /* SEND_OP_COND (SDC) */
#define CMD8 (0x40+8) /* SEND_IF_COND */
#define CMD9 (0x40+9) /* SEND_CSD */
#define CMD10 (0x40+10) /* SEND_CID */
#define CMD12 (0x40+12) /* STOP_TRANSMISSION */
#define ACMD13 (0xC0+13) /* SD_STATUS (SDC) */
#define CMD16 (0x40+16) /* SET_BLOCKLEN */
#define CMD17 (0x40+17) /* READ_SINGLE_BLOCK */
#define CMD18 (0x40+18) /* READ_MULTIPLE_BLOCK */
#define CMD23 (0x40+23) /* SET_BLOCK_COUNT (MMC) */
#define ACMD23 (0xC0+23) /* SET_WR_BLK_ERASE_COUNT (SDC) */
#define CMD24 (0x40+24) /* WRITE_BLOCK */
#define CMD25 (0x40+25) /* WRITE_MULTIPLE_BLOCK */
#define CMD55 (0x40+55) /* APP_CMD */
#define CMD58 (0x40+58) /* READ_OCR */
#define BOOL bool
#define CS_LOW() Chip_GPIO_SetPinOutLow(LPC_GPIO_PORT, 3, 0)
#define CS_HIGH() Chip_GPIO_SetPinOutHigh(LPC_GPIO_PORT, 3, 0)
#define FCLK_SLOW() /* Set slow clock (100k-400k) */
#define FCLK_FAST() /* Set fast clock (depends on the CSD) */
#define rcvr_spi_m(dst)
Functions
void SSPReceive (uint8_t *buf, uint32_t Length)
DSTATUS disk_initialize (BYTE drv)
DSTATUS disk_status (BYTE drv)
DRESULT disk_read (BYTE drv, BYTE *buff, DWORD sector, UINT count)
DRESULT disk_write (BYTE drv, const BYTE *buff, DWORD sector, UINT count)
void disk_timerproc (void)
Macro Definition Documentation
#define ACMD13 (0xC0+13) /* SD_STATUS (SDC) */
Definition at line 20 of file mmc.c.
Referenced by disk_write().
#define ACMD23 (0xC0+23) /* SET_WR_BLK_ERASE_COUNT (SDC) */
Definition at line 25 of file mmc.c.
Referenced by disk_write().
#define ACMD41 (0xC0+41) /* SEND_OP_COND (SDC) */
Definition at line 15 of file mmc.c.
Referenced by disk_initialize().
#define BOOL bool
Definition at line 31 of file mmc.c.
#define CMD0 (0x40+0) /* GO_IDLE_STATE */
Definition at line 13 of file mmc.c.
Referenced by disk_initialize().
#define CMD1 (0x40+1) /* SEND_OP_COND (MMC) */
Definition at line 14 of file mmc.c.
Referenced by disk_initialize().
#define CMD10 (0x40+10) /* SEND_CID */
Definition at line 18 of file mmc.c.
Referenced by disk_write().
#define CMD12 (0x40+12) /* STOP_TRANSMISSION */
Definition at line 19 of file mmc.c.
Referenced by disk_read().
#define CMD16 (0x40+16) /* SET_BLOCKLEN */
Definition at line 21 of file mmc.c.
Referenced by disk_initialize().
#define CMD17 (0x40+17) /* READ_SINGLE_BLOCK */
Definition at line 22 of file mmc.c.
Referenced by disk_read().
#define CMD18 (0x40+18) /* READ_MULTIPLE_BLOCK */
Definition at line 23 of file mmc.c.
Referenced by disk_read().
#define CMD23 (0x40+23) /* SET_BLOCK_COUNT (MMC) */
Definition at line 24 of file mmc.c.
#define CMD24 (0x40+24) /* WRITE_BLOCK */
Definition at line 26 of file mmc.c.
Referenced by disk_write().
#define CMD25 (0x40+25) /* WRITE_MULTIPLE_BLOCK */
Definition at line 27 of file mmc.c.
Referenced by disk_write().
#define CMD55 (0x40+55) /* APP_CMD */
Definition at line 28 of file mmc.c.
#define CMD58 (0x40+58) /* READ_OCR */
Definition at line 29 of file mmc.c.
Referenced by disk_initialize(), and disk_write().
#define CMD8 (0x40+8) /* SEND_IF_COND */
Definition at line 16 of file mmc.c.
Referenced by disk_initialize().
#define CMD9 (0x40+9) /* SEND_CSD */
Definition at line 17 of file mmc.c.
Referenced by disk_write().
#define CS_HIGH () Chip_GPIO_SetPinOutHigh(LPC_GPIO_PORT, 3, 0)
Definition at line 35 of file mmc.c.
#define CS_LOW () Chip_GPIO_SetPinOutLow(LPC_GPIO_PORT, 3, 0)
Definition at line 34 of file mmc.c.
#define FCLK_FAST () /* Set fast clock (depends on the CSD) */
Definition at line 38 of file mmc.c.
Referenced by disk_initialize().
#define FCLK_SLOW () /* Set slow clock (100k-400k) */
Definition at line 37 of file mmc.c.
Referenced by disk_initialize().
#define rcvr_spi_m (dst)
Value:
do { \
        SSPReceive((uint8_t*)(dst), 1); \
    } while(0)
Definition at line 110 of file mmc.c.
Function Documentation
DSTATUS disk_initialize (BYTE drv)
Definition at line 319 of file mmc.c.
References ACMD41, CMD0, CMD1, CMD16, CMD58, CMD8, CT_BLOCK, CT_MMC, CT_SD1, CT_SD2, FCLK_FAST, FCLK_SLOW, STA_NODISK, and STA_NOINIT.
Referenced by f_rename().
DRESULT disk_read (BYTE drv, BYTE * buff, DWORD sector, UINT count)
Definition at line 388 of file mmc.c.
References CMD12, CMD17, CMD18, CT_BLOCK, RES_ERROR, RES_NOTRDY, RES_OK, RES_PARERR, and STA_NOINIT.
Referenced by f_lseek(), f_open(), f_read(), f_rename(), and f_write().
DSTATUS disk_status (BYTE drv)
Definition at line 374 of file mmc.c.
References STA_NOINIT.
void disk_timerproc (void)
Definition at line 604 of file mmc.c.
References STA_NODISK, and STA_NOINIT.
Referenced by diskTickHook().
DRESULT disk_write (BYTE drv, const BYTE * buff, DWORD sector, UINT count)
Definition at line 426 of file mmc.c.
References ACMD13, ACMD23, CMD10, CMD24, CMD25, CMD58, CMD9, CT_BLOCK, CT_SD1, CT_SD2, CT_SDC, CTRL_POWER, CTRL_SYNC, disk_ioctl(), GET_BLOCK_SIZE, GET_SECTOR_COUNT, GET_SECTOR_SIZE, MMC_GET_CID, MMC_GET_CSD, MMC_GET_OCR, MMC_GET_SDSTAT, MMC_GET_TYPE, RES_ERROR, RES_NOTRDY, RES_OK, RES_PARERR, RES_WRPRT, STA_NOINIT, and STA_PROTECT.
Referenced by f_lseek(), f_read(), f_rename(), f_sync(), f_truncate(), and f_write().
void SSPReceive (uint8_t * buf, uint32_t Length)
Definition at line 69 of file mmc.c.