HMC+RTC=>SD: sapi_examples_AmA/edu-ciaa-nxp/ej22_SD_BrujulaIIC_RTC_Doc/inc/sapi_7_segment_display.h File Reference
sapi_7_segment_display.h File Reference
#include "sapi_datatypes.h"
#include "sapi_peripheral_map.h"
Macros
#define DISPLAY_7_SEGMENT_OFF 25
Functions
void display7SegmentTestPins (gpioMap_t *display7SegmentPins, gpioMap_t pin)
void display7SegmentPinConfig (gpioMap_t *display7SegmentPins)
void display7SegmentWrite (gpioMap_t *display7SegmentPins, uint8_t symbolIndex)
Macro Definition Documentation
#define DISPLAY_7_SEGMENT_OFF 25
Definition at line 44 of file sapi_7_segment_display.h.
Function Documentation
void display7SegmentPinConfig (gpioMap_t * display7SegmentPins)
Definition at line 182 of file sapi_7_segment_display.c.
References GPIO_OUTPUT, and gpioConfig().
void display7SegmentTestPins (gpioMap_t * display7SegmentPins, gpioMap_t pin)
Definition at line 164 of file sapi_7_segment_display.c.
References delay(), gpioWrite(), OFF, and ON.
void display7SegmentWrite (gpioMap_t * display7SegmentPins, uint8_t symbolIndex)
Definition at line 192 of file sapi_7_segment_display.c.
References display7SegmentOutputs, and gpioWrite().