HMC+RTC=>SD: sapi_examples_AmA/edu-ciaa-nxp/ej22_SD_BrujulaIIC_RTC_Doc/src/sapi_sct.c File Reference
sapi_sct.c File Reference
#include "sapi_sct.h"
Macros
#define CTOUT_FUNC FUNC1
Functions
void Sct_Init (uint32_t frequency)
void Sct_EnablePwmFor (uint8_t sctNumber)
uint32_t Sct_Uint8ToTicks (uint8_t value)
void Sct_SetDutyCycle (uint8_t sctNumber, uint8_t value)
uint8_t Sct_GetDutyCycle (uint8_t sctNumber)
Macro Definition Documentation
#define CTOUT_FUNC FUNC1
Definition at line 58 of file sapi_sct.c.
Referenced by Sct_EnablePwmFor().
Function Documentation
void Sct_EnablePwmFor (uint8_t sctNumber)
Definition at line 119 of file sapi_sct.c.
References CTOUT_FUNC, and Sct_SetDutyCycle().
uint8_t Sct_GetDutyCycle (uint8_t sctNumber)
Definition at line 158 of file sapi_sct.c.
Referenced by pwmRead().
void Sct_Init (uint32_t frequency)
Definition at line 105 of file sapi_sct.c.
void Sct_SetDutyCycle (uint8_t sctNumber, uint8_t value)
Definition at line 147 of file sapi_sct.c.
References Sct_Uint8ToTicks().
Referenced by pwmWrite(), and Sct_EnablePwmFor().
uint32_t Sct_Uint8ToTicks (uint8_t value)
Definition at line 135 of file sapi_sct.c.
Referenced by Sct_SetDutyCycle().