HMC+RTC=>SD: sapi_examples_AmA/edu-ciaa-nxp/ej22_SD_BrujulaIIC_RTC_Doc/inc/sapi_keypad.h File Reference
sapi_keypad.h File Reference
#include "sapi_datatypes.h"
#include "sapi_peripheral_map.h"
Data Structures
struct keypad_t
Functions
bool_t keypadConfig (keypad_t *keypad, gpioMap_t *keypadRowPins, uint8_t keypadRowSize, gpioMap_t *keypadColPins, uint8_t keypadColSize)
bool_t keypadRead (keypad_t *keypad, uint16_t *key)
Function Documentation
bool_t keypadConfig (keypad_t * keypad, gpioMap_t * keypadRowPins, uint8_t keypadRowSize, gpioMap_t * keypadColPins, uint8_t keypadColSize)
Definition at line 62 of file sapi_keypad.c.
References FALSE, GPIO_INPUT_PULLUP, GPIO_OUTPUT, gpioConfig(), keypad_t::keypadColPins, keypad_t::keypadColSize, keypad_t::keypadRowPins, keypad_t::keypadRowSize, and TRUE.
bool_t keypadRead (keypad_t * keypad, uint16_t * key)
Definition at line 98 of file sapi_keypad.c.
References delay(), FALSE, gpioRead(), gpioWrite(), HIGH, keypad_t::keypadColPins, keypad_t::keypadColSize, keypad_t::keypadRowPins, keypad_t::keypadRowSize, LOW, and TRUE.