HMC+RTC=>SD: sapi_examples_AmA/edu-ciaa-nxp/ej22_SD_BrujulaIIC_RTC_Doc/inc/sapi_i2c.h File Reference
sapi_i2c.h File Reference
#include "sapi_datatypes.h"
#include "sapi_peripheral_map.h"
Macros
#define I2C_SOFTWARE_SDA_DIR GPIO7
#define I2C_SOFTWARE_SDA_IN GPIO7
#define I2C_SOFTWARE_SDA_OUT GPIO7
#define I2C_SOFTWARE_SCL_DIR GPIO8
#define I2C_SOFTWARE_SCL_IN GPIO8
#define I2C_SOFTWARE_SCL_OUT GPIO8
#define I2C_SOFTWARE 0
#define SOFTWARE_I2C_DEBUG 0
Functions
bool_t i2cConfig (i2cMap_t i2cNumber, uint32_t clockRateHz)
bool_t i2cRead (i2cMap_t i2cNumber, uint8_t i2cSlaveAddress, uint8_t *dataToReadBuffer, uint16_t dataToReadBufferSize, bool_t sendWriteStop, uint8_t *receiveDataBuffer, uint16_t receiveDataBufferSize, bool_t sendReadStop)
bool_t i2cWrite (i2cMap_t i2cNumber, uint8_t i2cSlaveAddress, uint8_t *transmitDataBuffer, uint16_t transmitDataBufferSize, bool_t sendWriteStop)
Macro Definition Documentation
#define I2C_SOFTWARE 0
Definition at line 69 of file sapi_i2c.h.
#define I2C_SOFTWARE_SCL_DIR GPIO8
Definition at line 65 of file sapi_i2c.h.
#define I2C_SOFTWARE_SCL_IN GPIO8
Definition at line 66 of file sapi_i2c.h.
#define I2C_SOFTWARE_SCL_OUT GPIO8
Definition at line 67 of file sapi_i2c.h.
Referenced by i2cWrite().
#define I2C_SOFTWARE_SDA_DIR GPIO7
Definition at line 61 of file sapi_i2c.h.
Referenced by i2cWrite().
#define I2C_SOFTWARE_SDA_IN GPIO7
Definition at line 62 of file sapi_i2c.h.
Referenced by i2cWrite().
#define I2C_SOFTWARE_SDA_OUT GPIO7
Definition at line 63 of file sapi_i2c.h.
Referenced by i2cWrite().
#define SOFTWARE_I2C_DEBUG 0
Definition at line 70 of file sapi_i2c.h.
Function Documentation
bool_t i2cConfig (i2cMap_t i2cNumber, uint32_t clockRateHz)
Definition at line 349 of file sapi_i2c.c.
References FALSE.
Referenced by hmc5883lConfig().
bool_t i2cRead (i2cMap_t i2cNumber, uint8_t i2cSlaveAddress, uint8_t * dataToReadBuffer, uint16_t dataToReadBufferSize, bool_t sendWriteStop, uint8_t * receiveDataBuffer, uint16_t receiveDataBufferSize, bool_t sendReadStop)
Definition at line 367 of file sapi_i2c.c.
References FALSE.
Referenced by hmc5883lRead().
bool_t i2cWrite (i2cMap_t i2cNumber, uint8_t i2cSlaveAddress, uint8_t * transmitDataBuffer, uint16_t transmitDataBufferSize, bool_t sendWriteStop)
Definition at line 406 of file sapi_i2c.c.
References delayConfig(), delayRead(), FALSE, GPIO_INPUT_PULLUP, GPIO_OUTPUT, HIGH, I2C_SOFTWARE_SCL_OUT, I2C_SOFTWARE_SDA_DIR, I2C_SOFTWARE_SDA_IN, I2C_SOFTWARE_SDA_OUT, LOW, and TRUE.
Referenced by hmc5883lConfig().