HMC+RTC=>SD: sapi_examples_AmA/edu-ciaa-nxp/ej22_SD_BrujulaIIC_RTC_Doc/inc/sapi_hmc5883l.h File Reference
sapi_hmc5883l.h File Reference
#include "sapi_datatypes.h"
Data Structures
struct HMC5883L_config_t
Macros
#define HMC5883L_ADD 0x1E
#define HMC5883L_REG_CONFIG_A 0x00
#define HMC5883L_REG_CONFIG_B 0x01
#define HMC5883L_REG_MODE 0x02
#define HMC5883L_REG_X_MSB 0x03
#define HMC5883L_REG_X_LSB 0x04
#define HMC5883L_REG_Z_MSB 0x05
#define HMC5883L_REG_Z_LSB 0x06
#define HMC5883L_REG_Y_MSB 0x07
#define HMC5883L_REG_Y_LSB 0x08
#define HMC5883L_REG_STATUS 0x09
#define HMC5883L_REG_ID_REG_A 0x0A
#define HMC5883L_REG_ID_REG_B 0x0B
#define HMC5883L_REG_ID_REG_C 0x0C
#define HMC5883L_VALUE_ID_REG_A 0x48
#define HMC5883L_VALUE_ID_REG_B 0x34
#define HMC5883L_VALUE_ID_REG_C 0x33
Enumerations
enum HMC5883L_samples_t {
HMC5883L_1_sample = 0, HMC5883L_2_sample = 1, HMC5883L_4_sample = 2, HMC5883L_8_sample = 3,
HMC5883L_DEFAULT_sample = HMC5883L_1_sample
}
enum HMC5883L_rate_t {
HMC5883L_0_75_Hz = 0, HMC5883L_1_50_Hz = 1, HMC5883L_3_Hz = 2, HMC5883L_7_50_Hz = 3,
HMC5883L_15_Hz = 4, HMC5883L_30_Hz = 5, HMC5883L_75_Hz = 6, HMC5883L_DEFAULT_rate = HMC5883L_15_Hz
}
enum HMC5883L_messurement_t { HMC5883L_normal = 0, HMC5883L_positive = 1, HMC5883L_regative = 2, HMC5883L_DEFAULT_messurement = HMC5883L_normal }
enum HMC5883L_gain_t {
HMC5883L_1370 = 0, HMC5883L_1090 = 1, HMC5883L_820 = 2, HMC5883L_660 = 3,
HMC5883L_440 = 4, HMC5883L_390 = 5, HMC5883L_330 = 6, HMC5883L_230 = 7,
HMC5883L_DEFAULT_gain = HMC5883L_1090
}
enum HMC5883L_mode_t { HMC5883L_continuous_measurement = 0, HMC5883L_single_measurement = 1, HMC5883L_idle = 2, HMC5883L_DEFAULT_mode = HMC5883L_single_measurement }
Functions
bool_t hmc5883lIsAlive (void)
bool_t hmc5883lPrepareDefaultConfig (HMC5883L_config_t *config)
bool_t hmc5883lConfig (HMC5883L_config_t config)
bool_t hmc5883lRead (int16_t *x, int16_t *y, int16_t *z)
Macro Definition Documentation
#define HMC5883L_ADD 0x1E
Definition at line 52 of file sapi_hmc5883l.h.
Referenced by hmc5883lConfig(), and hmc5883lRead().
#define HMC5883L_REG_CONFIG_A 0x00
Definition at line 54 of file sapi_hmc5883l.h.
Referenced by hmc5883lConfig().
#define HMC5883L_REG_CONFIG_B 0x01
Definition at line 55 of file sapi_hmc5883l.h.
Referenced by hmc5883lConfig().
#define HMC5883L_REG_ID_REG_A 0x0A
Definition at line 70 of file sapi_hmc5883l.h.
#define HMC5883L_REG_ID_REG_B 0x0B
Definition at line 71 of file sapi_hmc5883l.h.
#define HMC5883L_REG_ID_REG_C 0x0C
Definition at line 72 of file sapi_hmc5883l.h.
#define HMC5883L_REG_MODE 0x02
Definition at line 57 of file sapi_hmc5883l.h.
Referenced by hmc5883lConfig().
#define HMC5883L_REG_STATUS 0x09
Definition at line 68 of file sapi_hmc5883l.h.
#define HMC5883L_REG_X_LSB 0x04
Definition at line 60 of file sapi_hmc5883l.h.
Referenced by hmc5883lRead().
#define HMC5883L_REG_X_MSB 0x03
Definition at line 59 of file sapi_hmc5883l.h.
Referenced by hmc5883lRead().
#define HMC5883L_REG_Y_LSB 0x08
Definition at line 66 of file sapi_hmc5883l.h.
Referenced by hmc5883lRead().
#define HMC5883L_REG_Y_MSB 0x07
Definition at line 65 of file sapi_hmc5883l.h.
Referenced by hmc5883lRead().
#define HMC5883L_REG_Z_LSB 0x06
Definition at line 63 of file sapi_hmc5883l.h.
Referenced by hmc5883lRead().
#define HMC5883L_REG_Z_MSB 0x05
Definition at line 62 of file sapi_hmc5883l.h.
Referenced by hmc5883lRead().
#define HMC5883L_VALUE_ID_REG_A 0x48
Definition at line 74 of file sapi_hmc5883l.h.
Referenced by hmc5883lIsAlive().
#define HMC5883L_VALUE_ID_REG_B 0x34
Definition at line 75 of file sapi_hmc5883l.h.
Referenced by hmc5883lIsAlive().
#define HMC5883L_VALUE_ID_REG_C 0x33
Definition at line 76 of file sapi_hmc5883l.h.
Referenced by hmc5883lIsAlive().
Enumeration Type Documentation
enum HMC5883L_gain_t
Enumerator
HMC5883L_1370
HMC5883L_1090
HMC5883L_820
HMC5883L_660
HMC5883L_440
HMC5883L_390
HMC5883L_330
HMC5883L_230
HMC5883L_DEFAULT_gain
Definition at line 106 of file sapi_hmc5883l.h.
enum HMC5883L_messurement_t
Enumerator
HMC5883L_normal
HMC5883L_positive
HMC5883L_regative
HMC5883L_DEFAULT_messurement
Definition at line 99 of file sapi_hmc5883l.h.
enum HMC5883L_mode_t
Enumerator
HMC5883L_continuous_measurement
HMC5883L_single_measurement
HMC5883L_idle
HMC5883L_DEFAULT_mode
Definition at line 118 of file sapi_hmc5883l.h.
enum HMC5883L_rate_t
Enumerator
HMC5883L_0_75_Hz
HMC5883L_1_50_Hz
HMC5883L_3_Hz
HMC5883L_7_50_Hz
HMC5883L_15_Hz
HMC5883L_30_Hz
HMC5883L_75_Hz
HMC5883L_DEFAULT_rate
Definition at line 88 of file sapi_hmc5883l.h.
enum HMC5883L_samples_t
Enumerator
HMC5883L_1_sample
HMC5883L_2_sample
HMC5883L_4_sample
HMC5883L_8_sample
HMC5883L_DEFAULT_sample
Definition at line 80 of file sapi_hmc5883l.h.
Function Documentation
bool_t hmc5883lConfig (HMC5883L_config_t config)
Definition at line 69 of file sapi_hmc5883l.c.
References HMC5883L_config_t::gain, HMC5883L_ADD, HMC5883L_REG_CONFIG_A, HMC5883L_REG_CONFIG_B, HMC5883L_REG_MODE, hmc5883lIsAlive(), i2cConfig(), i2cWrite(), HMC5883L_config_t::meassurement, HMC5883L_config_t::mode, HMC5883L_config_t::rate, HMC5883L_config_t::samples, and TRUE.
Referenced by main().
bool_t hmc5883lIsAlive (void)
Definition at line 40 of file sapi_hmc5883l.c.
References FALSE, HMC5883L_VALUE_ID_REG_A, HMC5883L_VALUE_ID_REG_B, HMC5883L_VALUE_ID_REG_C, and TRUE.
Referenced by hmc5883lConfig().
bool_t hmc5883lPrepareDefaultConfig (HMC5883L_config_t * config)
Definition at line 57 of file sapi_hmc5883l.c.
References HMC5883L_config_t::gain, HMC5883L_DEFAULT_gain, HMC5883L_DEFAULT_messurement, HMC5883L_DEFAULT_mode, HMC5883L_DEFAULT_rate, HMC5883L_DEFAULT_sample, HMC5883L_config_t::meassurement, HMC5883L_config_t::mode, HMC5883L_config_t::rate, HMC5883L_config_t::samples, and TRUE.
Referenced by main().
bool_t hmc5883lRead (int16_t * x, int16_t * y, int16_t * z)
TODO: return value must reflect the result of the operation
Definition at line 104 of file sapi_hmc5883l.c.
References HMC5883L_ADD, HMC5883L_REG_X_LSB, HMC5883L_REG_X_MSB, HMC5883L_REG_Y_LSB, HMC5883L_REG_Y_MSB, HMC5883L_REG_Z_LSB, HMC5883L_REG_Z_MSB, i2cRead(), and TRUE.
Referenced by main().