HMC+RTC=>SD: sapi_examples_AmA/edu-ciaa-nxp/ej22_SD_BrujulaIIC_RTC_Doc/src/sapi_servo.c File Reference
sapi_servo.c File Reference
#include "sapi_gpio.h"
#include "sapi_servo.h"
#include "sapi_timer.h"
Data Structures
struct attachedServo_t
Macros
#define EMPTY_POSITION 255
#define SERVO_TOTALNUMBER 9
#define SERVO_COMPLETECYCLE_PERIOD 20000 /*value in uSec */
#define SERVO_MAXUPTIME_PERIOD 2000 /*value in uSec */
#define SERVO_MINUPTIME_PERIOD 500 /*value in uSec */
Functions
bool_t servoConfig (servoMap_t servoNumber, servoConfig_t config)
uint8_t servoIsAttached (servoMap_t servoNumber)
uint16_t servoRead (servoMap_t servoNumber)
bool_t servoWrite (servoMap_t servoNumber, uint16_t angle)
Macro Definition Documentation
#define EMPTY_POSITION 255
Definition at line 48 of file sapi_servo.c.
Referenced by servoRead().
#define SERVO_COMPLETECYCLE_PERIOD 20000 /*value in uSec */
Definition at line 50 of file sapi_servo.c.
#define SERVO_MAXUPTIME_PERIOD 2000 /*value in uSec */
Definition at line 51 of file sapi_servo.c.
#define SERVO_MINUPTIME_PERIOD 500 /*value in uSec */
Definition at line 52 of file sapi_servo.c.
#define SERVO_TOTALNUMBER 9
Definition at line 49 of file sapi_servo.c.
Referenced by servoIsAttached().
Function Documentation
bool_t servoConfig (servoMap_t servoNumber, servoConfig_t config)
Definition at line 327 of file sapi_servo.c.
References SERVO_DISABLE, SERVO_DISABLE_OUTPUT, SERVO_ENABLE, and SERVO_ENABLE_OUTPUT.
uint8_t servoIsAttached (servoMap_t servoNumber)
Definition at line 363 of file sapi_servo.c.
References SERVO_TOTALNUMBER.
Referenced by servoRead(), and servoWrite().
uint16_t servoRead (servoMap_t servoNumber)
Definition at line 386 of file sapi_servo.c.
References EMPTY_POSITION, servoIsAttached(), and attachedServo_t::value.
bool_t servoWrite (servoMap_t servoNumber, uint16_t angle)
Definition at line 406 of file sapi_servo.c.
References FALSE, servoIsAttached(), TRUE, and attachedServo_t::value.