HMC+RTC=>SD: sapi_examples_AmA/edu-ciaa-nxp/ej22_SD_BrujulaIIC_RTC_Doc/src/sapi_gpio.c File Reference
sapi_gpio.c File Reference
#include "sapi_gpio.h"
Functions
bool_t gpioConfig (gpioMap_t pin, gpioConfig_t config)
bool_t gpioWrite (gpioMap_t pin, bool_t value)
bool_t gpioToggle (gpioMap_t pin)
bool_t gpioRead (gpioMap_t pin)
Variables
const pinConfigGpioLpc4337_t gpioPinsConfig []
Function Documentation
bool_t gpioConfig (gpioMap_t pin, gpioConfig_t config)
Definition at line 207 of file sapi_gpio.c.
References GPIO_ENABLE, GPIO_INPUT, GPIO_INPUT_PULLDOWN, GPIO_INPUT_PULLUP, GPIO_INPUT_PULLUP_PULLDOWN, and GPIO_OUTPUT.
Referenced by boardConfig(), display7SegmentPinConfig(), and keypadConfig().
bool_t gpioRead (gpioMap_t pin)
Definition at line 316 of file sapi_gpio.c.
References OFF.
Referenced by gpioToggle(), and keypadRead().
bool_t gpioToggle (gpioMap_t pin)
Definition at line 310 of file sapi_gpio.c.
References gpioRead(), and gpioWrite().
bool_t gpioWrite (gpioMap_t pin, bool_t value)
Definition at line 289 of file sapi_gpio.c.
Referenced by display7SegmentTestPins(), display7SegmentWrite(), gpioToggle(), keypadRead(), and main().
Variable Documentation
const pinConfigGpioLpc4337_t gpioPinsConfig[]
Definition at line 48 of file sapi_gpio.c.