HMC+RTC=>SD: sapi_examples_AmA/edu-ciaa-nxp/ej22_SD_BrujulaIIC_RTC_Doc/src/sapi_hmc5883l.c File Reference
sapi_hmc5883l.c File Reference
#include "sapi_hmc5883l.h"
#include "sapi_i2c.h"
Functions
bool_t hmc5883lIsAlive (void)
bool_t hmc5883lPrepareDefaultConfig (HMC5883L_config_t *config)
bool_t hmc5883lConfig (HMC5883L_config_t config)
bool_t hmc5883lRead (int16_t *x, int16_t *y, int16_t *z)
Function Documentation
bool_t hmc5883lConfig (HMC5883L_config_t config)
Definition at line 69 of file sapi_hmc5883l.c.
References HMC5883L_config_t::gain, HMC5883L_ADD, HMC5883L_REG_CONFIG_A, HMC5883L_REG_CONFIG_B, HMC5883L_REG_MODE, hmc5883lIsAlive(), i2cConfig(), i2cWrite(), HMC5883L_config_t::meassurement, HMC5883L_config_t::mode, HMC5883L_config_t::rate, HMC5883L_config_t::samples, and TRUE.
Referenced by main().
bool_t hmc5883lIsAlive (void)
Definition at line 40 of file sapi_hmc5883l.c.
References FALSE, HMC5883L_VALUE_ID_REG_A, HMC5883L_VALUE_ID_REG_B, HMC5883L_VALUE_ID_REG_C, and TRUE.
Referenced by hmc5883lConfig().
bool_t hmc5883lPrepareDefaultConfig (HMC5883L_config_t * config)
Definition at line 57 of file sapi_hmc5883l.c.
References HMC5883L_config_t::gain, HMC5883L_DEFAULT_gain, HMC5883L_DEFAULT_messurement, HMC5883L_DEFAULT_mode, HMC5883L_DEFAULT_rate, HMC5883L_DEFAULT_sample, HMC5883L_config_t::meassurement, HMC5883L_config_t::mode, HMC5883L_config_t::rate, HMC5883L_config_t::samples, and TRUE.
Referenced by main().
bool_t hmc5883lRead (int16_t * x, int16_t * y, int16_t * z)
TODO: return value must reflect the result of the operation
Definition at line 104 of file sapi_hmc5883l.c.
References HMC5883L_ADD, HMC5883L_REG_X_LSB, HMC5883L_REG_X_MSB, HMC5883L_REG_Y_LSB, HMC5883L_REG_Y_MSB, HMC5883L_REG_Z_LSB, HMC5883L_REG_Z_MSB, i2cRead(), and TRUE.
Referenced by main().