HMC+RTC=>SD: sapi_examples_AmA/edu-ciaa-nxp/ej22_SD_BrujulaIIC_RTC_Doc/src/sapi_uart.c File Reference
sapi_uart.c File Reference
#include "sapi_uart.h"
#include "string.h"
Macros
#define UART_485_LPC LPC_USART0 /* UART0 (RS485/Profibus) */
#define UART_USB_LPC LPC_USART2 /* UART2 (USB-UART) */
#define UART_232_LPC LPC_USART3 /* UART3 (RS232) */
Functions
waitForReceiveStringOrTimeoutState_t waitForReceiveStringOrTimeout (uartMap_t uart, waitForReceiveStringOrTimeout_t *instance)
bool_t waitForReceiveStringOrTimeoutBlocking (uartMap_t uart, char *string, uint16_t stringSize, tick_t timeout)
void uartConfig (uartMap_t uart, uint32_t baudRate)
bool_t uartReadByte (uartMap_t uart, uint8_t *receivedByte)
void uartWriteByte (uartMap_t uart, uint8_t byte)
void uartWriteString (uartMap_t uart, char *str)
__attribute__ ((section(".after_vectors")))
void UART2_IRQHandler (void)
void UART3_IRQHandler (void)
Macro Definition Documentation
#define UART_232_LPC LPC_USART3 /* UART3 (RS232) */
Definition at line 46 of file sapi_uart.c.
Referenced by uartConfig(), uartReadByte(), and uartWriteByte().
#define UART_485_LPC LPC_USART0 /* UART0 (RS485/Profibus) */
Definition at line 44 of file sapi_uart.c.
#define UART_USB_LPC LPC_USART2 /* UART2 (USB-UART) */
Definition at line 45 of file sapi_uart.c.
Referenced by uartConfig(), uartReadByte(), and uartWriteByte().
Function Documentation
__attribute__ ((section(".after_vectors")))
Definition at line 232 of file sapi_uart.c.
void UART2_IRQHandler (void)
Definition at line 239 of file sapi_uart.c.
void UART3_IRQHandler (void)
Definition at line 243 of file sapi_uart.c.
void uartConfig (uartMap_t uart, uint32_t baudRate)
Definition at line 146 of file sapi_uart.c.
References UART_232, UART_232_LPC, UART_485, UART_USB, and UART_USB_LPC.
bool_t uartReadByte (uartMap_t uart, uint8_t * receivedByte)
Definition at line 179 of file sapi_uart.c.
References FALSE, TRUE, UART_232, UART_232_LPC, UART_485, UART_USB, and UART_USB_LPC.
Referenced by waitForReceiveStringOrTimeout().
void uartWriteByte (uartMap_t uart, uint8_t byte)
Definition at line 206 of file sapi_uart.c.
References UART_232, UART_232_LPC, UART_485, UART_USB, and UART_USB_LPC.
Referenced by uartWriteString(), and waitForReceiveStringOrTimeout().
void uartWriteString (uartMap_t uart, char * str)
Definition at line 223 of file sapi_uart.c.
References uartWriteByte().
waitForReceiveStringOrTimeoutState_t waitForReceiveStringOrTimeout (uartMap_t uart, waitForReceiveStringOrTimeout_t * instance)
Definition at line 58 of file sapi_uart.c.
References waitForReceiveStringOrTimeout_t::delay, delayConfig(), delayRead(), waitForReceiveStringOrTimeout_t::state, waitForReceiveStringOrTimeout_t::string, waitForReceiveStringOrTimeout_t::stringIndex, waitForReceiveStringOrTimeout_t::stringSize, waitForReceiveStringOrTimeout_t::timeout, UART_RECEIVE_STRING_CONFIG, UART_RECEIVE_STRING_RECEIVED_OK, UART_RECEIVE_STRING_RECEIVING, UART_RECEIVE_STRING_TIMEOUT, UART_USB, uartReadByte(), and uartWriteByte().
Referenced by waitForReceiveStringOrTimeoutBlocking().
bool_t waitForReceiveStringOrTimeoutBlocking (uartMap_t uart, char * string, uint16_t stringSize, tick_t timeout)
Definition at line 118 of file sapi_uart.c.
References FALSE, waitForReceiveStringOrTimeout_t::state, waitForReceiveStringOrTimeout_t::string, waitForReceiveStringOrTimeout_t::stringSize, waitForReceiveStringOrTimeout_t::timeout, TRUE, UART_RECEIVE_STRING_CONFIG, UART_RECEIVE_STRING_RECEIVED_OK, UART_RECEIVE_STRING_TIMEOUT, and waitForReceiveStringOrTimeout().