HMC+RTC=>SD: sapi_examples_AmA/edu-ciaa-nxp/ej22_SD_BrujulaIIC_RTC_Doc/inc/sapi_delay.h File Reference
sapi_delay.h File Reference
#include "sapi_datatypes.h"
Data Structures
struct delay_t
Macros
#define INACCURATE_TO_MS 20400
#define INACCURATE_TO_US_x10 204
Functions
void delayInaccurate (tick_t delay)
void delayInaccurateUs (tick_t delay_us)
void delay (tick_t delay)
void delayConfig (delay_t *delay, tick_t duration)
bool_t delayRead (delay_t *delay)
void delayWrite (delay_t *delay, tick_t duration)
Macro Definition Documentation
#define INACCURATE_TO_MS 20400
Definition at line 52 of file sapi_delay.h.
Referenced by delayInaccurate().
#define INACCURATE_TO_US_x10 204
Definition at line 53 of file sapi_delay.h.
Referenced by delayInaccurateUs().
Function Documentation
void delay (tick_t delay)
Definition at line 81 of file sapi_delay.c.
References tickRateMS, and tickRead().
Referenced by delayInaccurate(), delayInaccurateUs(), display7SegmentTestPins(), keypadRead(), and main().
void delayConfig (delay_t * delay, tick_t duration)
Definition at line 89 of file sapi_delay.c.
References delay_t::duration, delay_t::running, and tickRateMS.
Referenced by i2cWrite(), main(), and waitForReceiveStringOrTimeout().
void delayInaccurate (tick_t delay)
Definition at line 59 of file sapi_delay.c.
References delay(), and INACCURATE_TO_MS.
void delayInaccurateUs (tick_t delay_us)
Definition at line 68 of file sapi_delay.c.
References delay(), and INACCURATE_TO_US_x10.
bool_t delayRead (delay_t * delay)
Definition at line 94 of file sapi_delay.c.
References delay_t::duration, delay_t::running, delay_t::startTime, and tickRead().
Referenced by i2cWrite(), main(), and waitForReceiveStringOrTimeout().
void delayWrite (delay_t * delay, tick_t duration)
Definition at line 112 of file sapi_delay.c.
References delay_t::duration, and tickRateMS.