HMC+RTC=>SD: sapi_examples_AmA/edu-ciaa-nxp/ej22_SD_BrujulaIIC_RTC_Doc/inc/sd_spi.h File Reference
sd_spi.h File Reference
Functions
void disk_timerproc (void)
int main (void)
Function Documentation
void disk_timerproc (void)
Definition at line 604 of file mmc.c.
References STA_NODISK, and STA_NOINIT.
Referenced by diskTickHook().
int main (void)
FUNCION PRINCIPAL, PUNTO DE ENTRADA AL PROGRAMA LUEGO DE ENCENDIDO O RESET.
–————————CONFIGURACIONES GENERALES–————————
Inicializar y configurar la plataforma
SPI configuration
Inicializar el conteo de Ticks con resolución de 10ms, con tickHook diskTickHook
—— Montaje de SD -——
—— Inicalizo HMC -——
declaro variables de retorno y pongo a medicion continua el sensor
—— Inicalizo RelojTiempoReal -——
pone en hora
–————————REPETIR POR SIEMPRE –————————
leer sensor HMC
___________Capa Aplicacion:actual<=>Capa Servicio:sapi_hmc5883l<=>Capa Interface:sapi_i2c<=>Capa Driver:i2c_18xx_43xx
si el delay ciclador lo indica hacer:
.....leer el RealTimeClock,
___________Capa Aplicacion:actual<=>Capa Servicio:N/A<=>Capa Interface:sapi_rtc<=>Capa Driver:rtc_18xx_43xx
.....completar el Buffer[],
.....escribir a SD,
___________Capa Aplicacion:actual<=>Capa Servicio:ff<=>Capa Interface:sapi_spi<=>Capa Driver:ssp_18xx_43xx
..... prender led segun corresponda:
..... Turn ON LEDG if the write operation was successful
..... Turn ON LEDR if the write operation was fail
-----------------------—FIN REPETIR POR SIEMPRE -----------------------—
Definition at line 163 of file sd_spi.c.
References boardConfig(), Buffer, BUFFERTAM, cargarDatosHMC(), cargarDatosRTC(), DATOSX, DATOSY, DATOSZ, delay(), delayConfig(), delayRead(), diskTickHook(), f_close(), f_mount(), f_open(), f_write(), FA_OPEN_APPEND, FA_WRITE, FILENAME, FR_OK, gpioWrite(), HMC5883L_8_sample, HMC5883L_continuous_measurement, hmc5883lConfig(), hmc5883lPrepareDefaultConfig(), hmc5883lRead(), rtc_t::hour, LEDG, LEDR, rtc_t::mday, rtc_t::min, HMC5883L_config_t::mode, rtc_t::month, OFF, ON, rtcConfig(), rtcRead(), HMC5883L_config_t::samples, rtc_t::sec, SPI0, spiConfig(), tickConfig(), TRUE, rtc_t::wday, and rtc_t::year.