HMC+RTC=>SD: sapi_examples_AmA/edu-ciaa-nxp/ej22_SD_BrujulaIIC_RTC_Doc/src/sd_spi.c File Reference
sd_spi.c File Reference
#include "rtc.h"
#include "sd_spi.h"
#include "sapi.h"
#include "ff.h"
Macros
#define FILENAME "Datos.txt"
nombre del archivo en el SD
#define DATOSX 26
posicion de datos Ascii X en el Buffer[]
#define DATOSY DATOSX + 7
posicion de datos Ascii Y respecto de X en el Buffer[]
#define DATOSZ DATOSY + 7
posicion de datos Ascii Z respecto de X en el Buffer[]
#define DATOSD 0
posicion de datos Ascii Dia en el Buffer[]
#define DATOSH 12
posicion de datos Ascii Hora respecto de dia en el Buffer[]
#define BUFFERTAM 47
tamaño del Buffer[]
Functions
char * itoa (int value, char *result, int base)
void cargarDatosRTC (rtc_t *rtc)
void cargarDatosHMC (int16_t ejeRaw, uint8_t Pos)
bool_t diskTickHook (void *ptr)
int main (void)
Variables
char Buffer [] = "DD/MM/YYYY, HH:MM:SS => X= ,Y= ,Z= \r\n"
Formacion de Buffer[] fijo a completar por cargarDatosRTC y cargarDatosHMC.
Macro Definition Documentation
#define BUFFERTAM 47
tamaño del Buffer[]
Definition at line 27 of file sd_spi.c.
Referenced by main().
#define DATOSD 0
posicion de datos Ascii Dia en el Buffer[]
Definition at line 25 of file sd_spi.c.
Referenced by cargarDatosRTC().
#define DATOSH 12
posicion de datos Ascii Hora respecto de dia en el Buffer[]
Definition at line 26 of file sd_spi.c.
Referenced by cargarDatosRTC().
#define DATOSX 26
posicion de datos Ascii X en el Buffer[]
Definition at line 22 of file sd_spi.c.
Referenced by main().
#define DATOSY DATOSX + 7
posicion de datos Ascii Y respecto de X en el Buffer[]
Definition at line 23 of file sd_spi.c.
Referenced by main().
#define DATOSZ DATOSY + 7
posicion de datos Ascii Z respecto de X en el Buffer[]
Definition at line 24 of file sd_spi.c.
Referenced by main().
#define FILENAME "Datos.txt"
nombre del archivo en el SD
Definition at line 21 of file sd_spi.c.
Referenced by main().
Function Documentation
void cargarDatosHMC (int16_t ejeRaw, uint8_t Pos)
cargarDatosHMC
Esta funcion es la encargada de escribir en Buffer[] los datos del Magnetometro HMC
Parameters
ejeRaw es un valor int16 crudo a convertir en ascii por itoa
Pos es la posicion dentro de Buffer[]
Note
uso una variable local itoBuffAux que se inicializa en espacios o sea limpio lo que retorna de itoa
Returns
void nada
El objetivo final es cargar Buffer[]
Definition at line 143 of file sd_spi.c.
References Buffer, diskTickHook(), and itoa().
Referenced by main().
void cargarDatosRTC (rtc_t * rtc)
cargarDatosRTC
Esta funcion es la encargada de escribir en Buffer[] los datos de RealTimeClock
Parameters
rtc es un puntero y apunta a la estructura de datos del RealTimeClock a convertir en ascii por itoa
Returns
void nada
DATOSD y DATOSH son indices definidos para no usar numeros magicos segun Note
Note
posicion ascii===========0123456789 0123456
fecha y hora en formato="DD/MM/YYYY, HH:MM:SS"
El objetivo final es cargar Buffer[]
Definition at line 81 of file sd_spi.c.
References Buffer, DATOSD, DATOSH, rtc_t::hour, itoa(), rtc_t::mday, rtc_t::min, rtc_t::month, rtc_t::sec, and rtc_t::year.
Referenced by main().
bool_t diskTickHook (void * ptr)
FUNCION que se ejecuta cada vezque ocurre un Tick
Definition at line 259 of file sd_spi.c.
References disk_timerproc().
Referenced by cargarDatosHMC(), and main().
char* itoa (int value, char * result, int base)
itoa = Integer To Ascii
Esta funcion es la encargada de convertir int value (pasado por referencia) y devolver un puntero a string con la cadena de caracterees de resultado
Parameters
value es un int y contiene una copia del valor a convertir
result es un puntero y apunta a la cadena de caracteres de respuesta
base es un int y se le pasa el tipo de sistema de numeracion: 2=binario; 10=decimal; 16=HEXA
Returns
retorna result idem a parametro result
Definition at line 48 of file sd_spi.c.
Referenced by cargarDatosHMC(), and cargarDatosRTC().
int main (void)
FUNCION PRINCIPAL, PUNTO DE ENTRADA AL PROGRAMA LUEGO DE ENCENDIDO O RESET.
–————————CONFIGURACIONES GENERALES–————————
Inicializar y configurar la plataforma
SPI configuration
Inicializar el conteo de Ticks con resolución de 10ms, con tickHook diskTickHook
—— Montaje de SD -——
—— Inicalizo HMC -——
declaro variables de retorno y pongo a medicion continua el sensor
—— Inicalizo RelojTiempoReal -——
pone en hora
–————————REPETIR POR SIEMPRE –————————
leer sensor HMC
___________Capa Aplicacion:actual<=>Capa Servicio:sapi_hmc5883l<=>Capa Interface:sapi_i2c<=>Capa Driver:i2c_18xx_43xx
si el delay ciclador lo indica hacer:
.....leer el RealTimeClock,
___________Capa Aplicacion:actual<=>Capa Servicio:N/A<=>Capa Interface:sapi_rtc<=>Capa Driver:rtc_18xx_43xx
.....completar el Buffer[],
.....escribir a SD,
___________Capa Aplicacion:actual<=>Capa Servicio:ff<=>Capa Interface:sapi_spi<=>Capa Driver:ssp_18xx_43xx
..... prender led segun corresponda:
..... Turn ON LEDG if the write operation was successful
..... Turn ON LEDR if the write operation was fail
-----------------------—FIN REPETIR POR SIEMPRE -----------------------—
Definition at line 163 of file sd_spi.c.
References boardConfig(), Buffer, BUFFERTAM, cargarDatosHMC(), cargarDatosRTC(), DATOSX, DATOSY, DATOSZ, delay(), delayConfig(), delayRead(), diskTickHook(), f_close(), f_mount(), f_open(), f_write(), FA_OPEN_APPEND, FA_WRITE, FILENAME, FR_OK, gpioWrite(), HMC5883L_8_sample, HMC5883L_continuous_measurement, hmc5883lConfig(), hmc5883lPrepareDefaultConfig(), hmc5883lRead(), rtc_t::hour, LEDG, LEDR, rtc_t::mday, rtc_t::min, HMC5883L_config_t::mode, rtc_t::month, OFF, ON, rtcConfig(), rtcRead(), HMC5883L_config_t::samples, rtc_t::sec, SPI0, spiConfig(), tickConfig(), TRUE, rtc_t::wday, and rtc_t::year.
Variable Documentation
char Buffer[] = "DD/MM/YYYY, HH:MM:SS => X= ,Y= ,Z= \r\n"
Formacion de Buffer[] fijo a completar por cargarDatosRTC y cargarDatosHMC.
Definition at line 34 of file sd_spi.c.
Referenced by cargarDatosHMC(), cargarDatosRTC(), and main().